---
- name: Update apt
  ansible.builtin.apt:
    update_cache: true

- name: Install packages
  ansible.builtin.apt:
    name: '{{ install_packages }}'
    state: present

- name: UFW - Allow HTTP
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: UFW - Allow HTTPS
  community.general.ufw:
    rule: allow
    port: '443'
    proto: tcp

- name: UFW - Allow HAProxy Stats
  community.general.ufw:
    rule: allow
    port: '32700'
    proto: tcp

- name: Create self-signed certificate
  ansible.builtin.command: >
     /usr/bin/openssl req -x509 -nodes -subj '/CN={{ ansible_hostname }}'
     -days 3650 -newkey rsa:4096 -sha256 -keyout {{ haproxy_priv_key }} -out {{ haproxy_cert }}
  changed_when: true

- name: Combine the two parts of the certificate
  ansible.builtin.shell: /usr/bin/cat {{ haproxy_cert }} {{ haproxy_priv_key }} > {{ haproxy_combined_cert }}
  changed_when: true

- name: Copy a version of haproxy.cfg.j2 into /etc/haproxy/haproxy.cfg
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'
    backup: true

- name: Restart haproxy service
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: haproxy
