---
- name: Restart service postgresql
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: postgresql

- name: Wait for postgresql to be running
  ansible.builtin.service_facts:
  register: result
  until: result.ansible_facts.services['postgresql'].state == 'running'
  retries: 10
  delay: 10

- name: Unconditionally reboot the machine
  ansible.builtin.reboot:
    reboot_timeout: 60
