---
## PostgreSQL

postgresql_conf:
  listen_addresses: '*'
  max_connections: '32'
  shared_buffers: '256MB'
  effective_cache_size: '2GB'
  max_prepared_transactions: '32'
  max_locks_per_transaction: '64'
  work_mem: '4MB'
  maintenance_work_mem: '128MB'
  vacuum_cost_delay: '10'
  synchronous_commit: 'off'
  checkpoint_timeout: '15min'
  checkpoint_completion_target: '0.9'
  seq_page_cost: '1.0'
  random_page_cost: '1.1'
  logging_collector: 'off'
  log_directory: 'pg_log'
  log_filename: 'postgresql-%Y-%m-%d_%H%M%S.log'
  log_truncate_on_rotation: 'on'
  log_rotation_age: '1d'
  log_min_messages: 'warning'
  log_min_error_statement: 'error'
  log_min_duration_statement: '1000'
  log_line_prefix: '%m|%l|%d|%r|%p|%i|%c|%s|%v|%x|%u| '
  autovacuum: 'on'
  log_autovacuum_min_duration: '0'
  autovacuum_max_workers: '10'
  autovacuum_naptime: '1min'
  autovacuum_vacuum_threshold: '50'
  max_worker_processes: '8'
  max_parallel_workers_per_gather: '2'
  max_parallel_workers: '4'
  wal_buffers: 4MB
  min_wal_size: 128MB
  max_wal_size: 256MB
  default_statistics_target: '100'
  effective_io_concurrency: '128'
  shared_preload_libraries: 'timescaledb'

## TimeScaleDB
timescaledb_max_background_workers: 8
