---
- name: Update apt
  ansible.builtin.apt:
    update_cache: true

- name: Install packages
  ansible.builtin.apt:
    name: '{{ dependencies }}'
    state: present

- name: Add repositories for GitLab-CE
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      /usr/bin/curl -sS {{ gitlab_url_repo }} | /usr/bin/bash
  changed_when: true
  args:
    executable: /bin/bash

- name: Install the gitlab-ce main package
  ansible.builtin.apt:
    name: '{{ gitlab_package }}'
    state: present
    update_cache: true

- name: UFW - Allow HTTPS
  community.general.ufw:
    rule: allow
    port: '443'
    proto: tcp

# Changes to the gitlab's configuration file

- name: Change external url
  ansible.builtin.lineinfile:
    path: /etc/gitlab/gitlab.rb
    state: present
    backup: true
    regexp: '^external_url'
    line: "external_url '{{ gitlab_external_url }}'"

- name: PostgreSQL configuration
  ansible.builtin.blockinfile:
    path: /etc/gitlab/gitlab.rb
    state: present
    backup: true
    marker: "### {mark} ANSIBLE MANAGED BLOCK ###"
    block: |
      ### Gravatar Settings
      gitlab_rails['gravatar_ssl_url'] = '{{ gitlab_gravatar }}'
      # Disable the built-in Postgres
      postgresql['enable'] = false
      # Fill in the connection details for database.yml
      gitlab_rails['db_adapter'] = 'postgresql'
      gitlab_rails['db_encoding'] = 'utf8'
      gitlab_rails['db_host'] = '{{ host_postgresql }}'
      gitlab_rails['db_port'] = '{{ port_postgresql }}'
      gitlab_rails['db_username'] = '{{ gitlab_user_database }}'
      gitlab_rails['db_password'] = '{{ gitlab_user_database_password }}'
      gitlab_rails['db_database'] = '{{ gitlab_name_database }}'
      # Let's Encrypt
      letsencrypt['enable'] = false
      # GitLab email server settings
      gitlab_rails['smtp_enable'] = true
      gitlab_rails['smtp_address'] = 'smtp.gmail.com'
      gitlab_rails['smtp_port'] = 587
      gitlab_rails['smtp_user_name'] = '{{ gitlab_gmail_account }}'
      gitlab_rails['smtp_password'] = '{{ gitlab_gmail_password }}'
      gitlab_rails['smtp_domain'] = 'smtp.gmail.com'
      gitlab_rails['smtp_authentication'] = 'login'
      gitlab_rails['smtp_enable_starttls_auto'] = true
      gitlab_rails['smtp_tls'] = false
      gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
        # Can be: 'none', 'peer', 'client_once', 'fail_if_no_peer_cert', see http://api.rubyonrails.org/classes/ActionMailer/Base.html
      # Added extra configuration to limit too much connections to PostgreSQL
      sidekiq['concurrency'] = 1

- name: Reconfigure GitLab to make the changes take effect
  ansible.builtin.command: >
    /usr/bin/gitlab-ctl reconfigure || /bin/true
  changed_when: true
