---
# Data got from zabbix documentation:
#  https://www.zabbix.com/download?zabbix=7.0&os_distribution=ubuntu&os_version=24.04&components=server_frontend_agent&db=pgsql&ws=nginx
# After selecting the options:
#  - Verison: 7.0
#  - OS Distribution: Ubuntu
#  - OS Version: 24.04 (Noble)
#  - Database: PostgreSQL
#  - Web Server: Nginx

zabbix_repository_package_url: https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_7.0-1+ubuntu24.04_all.deb
install_packages:
  - zabbix-server-pgsql
  - zabbix-frontend-php
  - php8.3-pgsql
  - php8.3-curl
  - zabbix-nginx-conf
  - zabbix-sql-scripts
  - zabbix-agent2
install_packages_psql:
  - postgresql-client-common
  - postgresql-client-16
zabbix_schema_path: /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz
zabbix_schema_timescaledb_path: /usr/share/zabbix-sql-scripts/postgresql/timescaledb/schema.sql
postgresql_conn: |
  /usr/bin/psql -U {{ zabbix_user_database }} -h {{ hostvars['postgresql'].ansible_host }} {{ zabbix_name_database }}
zabbix_services: ['zabbix-server', 'zabbix-agent2', 'nginx', 'php8.3-fpm']
